// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ItemConverterDTO.ItemsJsonTypes;

namespace ItemConverterDTO.ItemsJsonTypes
{

    internal class ItemStats
    {

        [JsonProperty("FlatMovementSpeedMod")]
        public double FlatMovementSpeedMod { get; set; }
    }

}
