// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace RitoConnector
{
    internal abstract class ItemStats
    {
        [JsonProperty("FlatMovementSpeedMod")]
        public double FlatMovementSpeedMod { get; set; }
    }
}