// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace RitoConnector
{

    public class MatchhistoryDto
    {

        [JsonProperty("summonerId")]
        public int SummonerId { get; set; }

        [JsonProperty("games")]
        public Game[] Games { get; set; }
    }

}
