// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace RitoConnector
{
    public abstract class RankedDto
    {
        [JsonProperty("standard")]
        public RankedId[] RankedId { get; set; }
    }
}