// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace RitoConnector
{

    public class RunePagesDto
    {

        [JsonProperty("pages")]
        public Page[] Pages { get; set; }

        [JsonProperty("summonerId")]
        public int SummonerId { get; set; }
    }

}
