// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace RitoConnector
{

    public class Slot
    {

        [JsonProperty("runeId")]
        public int RuneId { get; set; }

        [JsonProperty("runeSlotId")]
        public int RuneSlotId { get; set; }
    }

}
